version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: e-invoicing-app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=einvoicedb
      - DB_USERNAME=root
      - DB_PASSWORD=rootpass
    depends_on:
      - mysql
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: e-invoicing-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: e-invoicing-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: e-invoicing-mysql
    restart: unless-stopped
    environment:
        - MYSQL_ROOT_PASSWORD=rootpass
        - MYSQL_DATABASE=einvoicedb
        - MYSQL_USER=myuser
        - MYSQL_PASSWORD=mypass
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3032:3306"
    networks:
      - app-network

  composer:
    image: composer/composer:latest-bin
    container_name: e-invoicing-composer
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - app
    profiles:
      - donotstart
    networks:
      - app-network

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: e-invoicing-artisan
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql
    profiles:
      - donotstart
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: e-invoicing-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
